name: Build and publish new version of @intersect.mbo/pdf-ui package
run-name: Publish by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: pdf-ui

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Install dependencies
        run: npm ci
        env:
          NODE_OPTIONS: --max_old_space_size=8192

      - name: Publish to npm
        run: npm publish --access public --tag beta
        env:
          NODE_OPTIONS: --max_old_space_size=8192
